cmake_minimum_required(VERSION 2.6)
	add_executable(	arithmetic arithmetic.cpp 
logicalop logicalop.cpp 
bitwiseop bitwiseop.cpp 
miscelleneousoperator miscelleneousoperator.cpp 
simpleif_else simpleif_else.cpp 
conditionalLoop conditionalLoop.cpp 
break break.cpp 
continue continue.cpp 
goto goto.cpp 
rValue_lValue rValue_lValue.cpp 
call_by_ref call_by_ref.cpp 
recursion recursion.cpp 
auto auto.cpp 
static static.cpp 
extern extern.cpp 
mutable mutable.cpp 
stringLiterals stringLiterals.cpp 
Digit_separators Digit_separators.cpp 
classTemplates classTemplates.cpp 
staticMember staticMember.cpp 
object object.cpp 
Constructor Constructor.cpp 
constructorOverloading constructorOverloading.cpp 
copy_constructor copy_constructor.cpp 
destructor destructor.cpp 
this this.cpp 
staticMember staticMember.cpp 
enum enum.cpp 
enumeration enumeration.cpp 
enumeration_class enumeration_class.cpp 
friendFunction friendFunction.cpp 
multipleInheritance multipleInheritance.cpp 
singleInheritance singleInheritance.cpp 
polymorphism polymorphism.cpp 
constructorOverloading constructorOverloading.cpp 
operatorOverloading operatorOverloading.cpp 
overide_final overide_final.cpp 
virtual virtual.cpp 
pure_virtual pure_virtual.cpp 
abstract abstract.cpp 
interface interface.cpp 
nameSpace nameSpace.cpp 
exceptionalHandling exceptionalHandling.cpp 
template template.cpp 
classTemplates classTemplates.cpp 
functionalTemplates functionalTemplates.cpp 
signal signal.cpp 
file_opn file_opn.cpp 
vector vector.cpp 
begin_end begin_end.cpp 
next_prev next_prev.cpp 
advance advance.cpp 
inserter inserter.cpp 
tuple tuple.cpp 
abstract_class abstract_class.cpp 
multipleInheritance multipleInheritance.cpp 
typedef typedef.cpp 
try try.cpp 
throw throw.cpp 
private private.cpp 
break break.cpp 
catch catch.cpp 
reinterpret_cast reinterpret_cast.cpp 
class class.cpp 
protected protected.cpp 
case case.cpp 
struct struct.cpp 
bool bool.cpp 
for for.cpp 
union union.cpp 
register register.cpp 	)